apiVersion: v1
kind: PersistentVolume
metadata:
  name: mariadb-pv
  labels:
    name: mariadb
spec:
  storageClassName: standard
  capacity:
    storage: {{.Values.mariadb_pv_size}} 
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce # All Pods from the same node can access this Persistent Volume(PV)
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: {{.Values.nfs_server_ip}} 
    path: {{.Values.mariadb_pv_nfs_path}} 
