apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-pv
  labels:
    name: wordpress
spec:
  storageClassName: standard
  capacity: 
    storage: {{.Values.wordpress_pv_size}} 
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: {{.Values.nfs_server_ip}} 
    path: {{.Values.wordpress_pv_nfs_path}} 
