apiVersion: v1
kind: PersistentVolume
metadata:
  name: mariadb-pv
  labels:
    name: mariadb
spec:
  storageClassName: standard
  capacity:
    storage: 100Mi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce # All Pods from the same node can access this Persistent Volume(PV)
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.1.108 # Replace this IP address with your NFS Server IP Address
    path: /var/nfs/jegan/mariadb
