apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-pv
  labels:
    name: wordpress
spec:
  storageClassName: standard
  capacity: 
    storage: 100Mi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.1.108
    path: /var/nfs/jegan/wordpress
