apiVersion: apps/v1
kind: StatefulSet 
metadata:
  labels:
    app: mariadb
  name: mariadb
spec:
  selector:
    matchLabels:
      app: mariadb
  replicas: 3
  volumeClaimTemplates:
  - metadata:
      name: mariadb-storage
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: standard
      resources:
        requests:
          storage: 100Mi
  template:
    metadata:
      labels:
        app: mariadb
    spec:

      containers:
      - name: mariadb
        image: bitnami/mariadb:latest

        volumeMounts:
        - name: mariadb-storage
          mountPath: /bitnami/mariadb/data

        env:
        - name: MARIADB_ROOT_PASSWORD
          value: root@123

        - name: MARIADB_DATABASE
          value: wordpress
