apiVersion: apps/v1
kind: ReplicaSet
metadata:
  labels:
    app: nginx
    pod-template-hash: rs 
  name: nginx-rs
  namespace: jegan
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginx
      pod-template-hash: rs 
  template:
    metadata:
      labels:
        app: nginx
        pod-template-hash: rs 
    spec:
      containers:
      - image: nginx:1.18
        imagePullPolicy: IfNotPresent
        name: nginx
